#!/bin/bash

# Configuration
dev=/dev/ttyUSB0
baud=9600

if [ "$1" == "" ]; then
  echo "Please enter file..."
  exit
fi

# Remove suffix
file="${1%.*}"

# Make the project (Only needed for C)
#make -f nbproject/Makefile-default.mk SUBPROJECTS= .build-conf

# Generate HEX Code
echo MPASMX
"/opt/microchip/mplabx/v3.51/mpasmx/mpasmx" -p18f4620 -rDEC -o$file.o $file.asm 
cat $file.ERR
echo 

mv $file.LST debug/$file.LST 
"/opt/microchip/mplabx/v3.51/mpasmx/mplink" -p18f4620 $file.o   

# Cleanup
mv -f a.hex $file.hex 2> /dev/null
rm -f *.out 2> /dev/null
rm -f *.ERR 2> /dev/null
rm -f *.COD 2> /dev/null
rm -f ___* 2> /dev/null
rm "$file.o" 2> /dev/null

# Set up device using same settings as used by screen
stty -F $dev 406:0:8bd:8a30:3:1c:7f:8:4:2:64:0:11:13:1a:0:12:f:17:16:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0 

# Wait for reset button
echo Waiting for reset button press...
head -n 1 $dev | grep -qe ">"
printf "\r" > $dev
sleep 3
cat "$file.hex" > $dev

# Delete hex file
rm "$file.hex"

echo
echo done!
